name: Run-Testfiles

on:
  push:
    branches-ignore:
      - master
  
  pull_request:
    branches:
      master

jobs:
  Compilation:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Compile
        run:  make release "FATALWARN=t"
  
  Testing:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        file: ["test/testfile.txt"]
    
      fail-fast: true

    steps:
      - name: Run testfile
        run: bin/hhfi ${{ matrix.file }}
