name: Run-Testfiles

on:
  push:
    branches-ignore:
      - master
  
  pull_request:
    branches:
      master

jobs:
  Compilation:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

      fail-fast: true
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Compile
        run:  make release "FATALWARN=t"
      
      - name: Save Binary
        uses: actions/upload-artifact@v1
        with:
          name: bin${{ matrix.os }}
          path: bin/hhfi
      
      - name: Check folder
        if: ${{matrix.os}} == "windows-latest"
        run: dir bin
  
  Testing:
    needs: Compilation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        file: ["testfile.txt", "testfile2.txt"]
    
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Make Binary Directory
        run: mkdir bin

      - name: Get Binary
        uses: actions/download-artifact@v1
        with:
          name: bin${{ matrix.os }}

      - name: Run Testfile
        run: bin/hhfi test/${{ matrix.file }}
