name: Run-Testfiles

on:
  push:
    branches-ignore:
      - master
  
  pull_request:
    branches:
      master

jobs:
  Compilation:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

      fail-fast: true
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Compile
        run:  make release "FATALWARN=t"

      - name: Save Exe
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v1
        with:
          name: bin${{ matrix.os }}
          path: bin/hhfi.exe

      - name: Save Binary
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v1
        with:
          name: bin${{ matrix.os }}
          path: bin/hhfi
  



  Testing:
    needs: Compilation
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        file: ["testfile.txt", "testfile2.txt"]
    
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Get Binary
        uses: actions/download-artifact@v1
        with:
          name: bin${{ matrix.os }}

      - name: Check Binary Permissions
        if: matrix.os != 'windows-latest'
        run: chmod +x bin${{ matrix.os }}/*

      - name: Run Testfile Unix
        if: matrix.os != 'windows-latest'
        run: bin${{ matrix.os }}/hhfi test/${{ matrix.file }}
      
      - name: Run Testfile Windows
        if: matrix.os == 'windows-latest'
        run: binwindows-latest/hhfi.exe test/${{ matrix.file }}
